-- Insert CBC subjects for Grade 4-9
INSERT INTO public.subjects (name, code, level) VALUES
-- Core subjects for upper primary (Grade 4-6)
('English', 'ENG', 'upper_primary'),
('Kiswahili', 'KIS', 'upper_primary'),
('Kenyan Sign Language (KSL)', 'KSL', 'upper_primary'),
('Mathematics', 'MAT', 'upper_primary'),
('Science and Technology', 'SCI', 'upper_primary'),
('Social Studies', 'SOC', 'upper_primary'),
('Agriculture', 'AGR', 'upper_primary'),
('Home Science', 'HMS', 'upper_primary'),
('Religious Education (CRE)', 'CRE', 'upper_primary'),
('Religious Education (IRE)', 'IRE', 'upper_primary'),
('Religious Education (HRE)', 'HRE', 'upper_primary'),
('Life Skills Education', 'LSE', 'upper_primary'),
('Creative Arts', 'CRA', 'upper_primary'),
('Visual Arts', 'VIS', 'upper_primary'),
('Performing Arts', 'PER', 'upper_primary'),
('Pre-Technical and Pre-Career Education', 'PTC', 'upper_primary'),
('Physical and Health Education', 'PHE', 'upper_primary'),
('Health Education', 'HED', 'upper_primary'),
('Computer Science', 'COM', 'upper_primary'),
('Indigenous Languages', 'IND', 'upper_primary'),
('French', 'FRE', 'upper_primary'),
('German', 'GER', 'upper_primary'),
('Mandarin', 'MAN', 'upper_primary'),
('Arabic', 'ARA', 'upper_primary'),

-- Subjects for junior secondary (Grade 7-9)
('Integrated Science', 'INT_SCI', 'junior_secondary'),
('Business Studies', 'BUS', 'junior_secondary'),
('English (JS)', 'ENG_JS', 'junior_secondary'),
('Kiswahili (JS)', 'KIS_JS', 'junior_secondary'),
('Mathematics (JS)', 'MAT_JS', 'junior_secondary'),
('Agriculture (JS)', 'AGR_JS', 'junior_secondary'),
('Home Science (JS)', 'HMS_JS', 'junior_secondary'),
('Religious Education CRE (JS)', 'CRE_JS', 'junior_secondary'),
('Religious Education IRE (JS)', 'IRE_JS', 'junior_secondary'),
('Religious Education HRE (JS)', 'HRE_JS', 'junior_secondary'),
('Life Skills Education (JS)', 'LSE_JS', 'junior_secondary'),
('Creative Arts (JS)', 'CRA_JS', 'junior_secondary'),
('Visual Arts (JS)', 'VIS_JS', 'junior_secondary'),
('Performing Arts (JS)', 'PER_JS', 'junior_secondary'),
('Physical and Health Education (JS)', 'PHE_JS', 'junior_secondary'),
('Computer Science (JS)', 'COM_JS', 'junior_secondary'),
('French (JS)', 'FRE_JS', 'junior_secondary'),
('German (JS)', 'GER_JS', 'junior_secondary'),
('Mandarin (JS)', 'MAN_JS', 'junior_secondary'),
('Arabic (JS)', 'ARA_JS', 'junior_secondary');