// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdpqwkbkuqypzzuphmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZHBxd2tia3VxeXB6enVwaG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTExNTAsImV4cCI6MjA2ODI2NzE1MH0.paCwBEmKBkPAzj5z-_kEWfuBWKLFYcTEBgstH1Xans8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});